<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DOLAP146" ignored="0" name="TotalWeightPackagingUnitsFunctionality" tests="2" failures="1" timestamp="29 Jan 2019 10:09:35 GMT" time="87.331" errors="0">
  <testcase name="totalPackagingUnitValidation" time="62.855" classname="tests.TotalWeightPackagingUnitsFunctionalTests"/>
  <testcase name="totalShipmentWeightValidation" time="5.359" classname="tests.TotalWeightPackagingUnitsFunctionalTests">
    <failure type="java.lang.AssertionError" message="expected [0] but found [3]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [3]
at utilities.CommonFunctions.validationEquals(CommonFunctions.java:98)
at tests.TotalWeightPackagingUnitsFunctionalTests.totalShipmentWeightValidation(TotalWeightPackagingUnitsFunctionalTests.java:95)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- totalShipmentWeightValidation -->
</testsuite> <!-- TotalWeightPackagingUnitsFunctionality -->
